"""sync models with current db diagram

Revision ID: c828a5b82cf5
Revises: debb945a95a8
Create Date: 2026-06-06 11:51:15.273197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'c828a5b82cf5'
down_revision: Union[str, Sequence[str], None] = 'debb945a95a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('address_id', sa.Uuid(), nullable=False),
    sa.Column('street', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('postal_code', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('address_id')
    )
    op.create_table('car_status',
    sa.Column('car_status_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('car_status_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('car_type',
    sa.Column('car_type_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('car_type_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('discount',
    sa.Column('discount_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('percent_value', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('discount_id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('fuel_type',
    sa.Column('fuel_type_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('fuel_type_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('invoice_status',
    sa.Column('invoice_status_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('invoice_status_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('payment_method',
    sa.Column('payment_method_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('payment_method_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('payment_status',
    sa.Column('payment_status_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('payment_status_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rental_status',
    sa.Column('rental_status_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('rental_status_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('transmission',
    sa.Column('transmission_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('transmission_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('customer',
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('address_id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('driver_license_no', sa.String(), nullable=True),
    sa.Column('license_expiry_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['address.address_id'], ),
    sa.PrimaryKeyConstraint('customer_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('location',
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('address_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['address.address_id'], ),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_table('car',
    sa.Column('car_id', sa.Uuid(), nullable=False),
    sa.Column('current_location_id', sa.Uuid(), nullable=False),
    sa.Column('fuel_type_id', sa.Uuid(), nullable=False),
    sa.Column('transmission_id', sa.Uuid(), nullable=False),
    sa.Column('car_type_id', sa.Uuid(), nullable=False),
    sa.Column('car_status_id', sa.Uuid(), nullable=False),
    sa.Column('vin', sa.String(), nullable=False),
    sa.Column('plate_number', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('production_year', sa.SmallInteger(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('seats', sa.SmallInteger(), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=False),
    sa.Column('daily_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['car_status_id'], ['car_status.car_status_id'], ),
    sa.ForeignKeyConstraint(['car_type_id'], ['car_type.car_type_id'], ),
    sa.ForeignKeyConstraint(['current_location_id'], ['location.location_id'], ),
    sa.ForeignKeyConstraint(['fuel_type_id'], ['fuel_type.fuel_type_id'], ),
    sa.ForeignKeyConstraint(['transmission_id'], ['transmission.transmission_id'], ),
    sa.PrimaryKeyConstraint('car_id'),
    sa.UniqueConstraint('plate_number'),
    sa.UniqueConstraint('vin')
    )
    op.create_table('rental',
    sa.Column('rental_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('car_id', sa.Uuid(), nullable=False),
    sa.Column('pickup_location_id', sa.Uuid(), nullable=False),
    sa.Column('return_location_id', sa.Uuid(), nullable=False),
    sa.Column('rental_status_id', sa.Uuid(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('planned_end_date', sa.DateTime(), nullable=False),
    sa.Column('actual_end_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['car.car_id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], ),
    sa.ForeignKeyConstraint(['pickup_location_id'], ['location.location_id'], ),
    sa.ForeignKeyConstraint(['rental_status_id'], ['rental_status.rental_status_id'], ),
    sa.ForeignKeyConstraint(['return_location_id'], ['location.location_id'], ),
    sa.PrimaryKeyConstraint('rental_id')
    )
    op.create_table('invoice',
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('rental_id', sa.Uuid(), nullable=False),
    sa.Column('discount_id', sa.Uuid(), nullable=True),
    sa.Column('invoice_status_id', sa.Uuid(), nullable=False),
    sa.Column('payment_method_id', sa.Uuid(), nullable=True),
    sa.Column('payment_status_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_number', sa.String(), nullable=False),
    sa.Column('invoice_issue_date', sa.Date(), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['discount_id'], ['discount.discount_id'], ),
    sa.ForeignKeyConstraint(['invoice_status_id'], ['invoice_status.invoice_status_id'], ),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_method.payment_method_id'], ),
    sa.ForeignKeyConstraint(['payment_status_id'], ['payment_status.payment_status_id'], ),
    sa.ForeignKeyConstraint(['rental_id'], ['rental.rental_id'], ),
    sa.PrimaryKeyConstraint('invoice_id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.drop_index(op.f('ix_rentals_id'), table_name='rentals')
    op.drop_table('rentals')
    op.drop_index(op.f('ix_cars_id'), table_name='cars')
    op.drop_table('cars')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_discounts_id'), table_name='discounts')
    op.drop_table('discounts')
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - adjusted for FK dependency order ###
    op.create_table('locations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('street', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('postal_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('locations_pkey'))
    )
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    op.create_table('discounts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('percent_value', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('valid_from', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('valid_to', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DateTime(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('discounts_pkey')),
    sa.UniqueConstraint('code', name=op.f('discounts_code_key'))
    )
    op.create_index(op.f('ix_discounts_id'), 'discounts', ['id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('driver_license_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('license_expiry_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('street', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('postal_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DateTime(), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.DateTime(), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('customers_pkey')),
    sa.UniqueConstraint('email', name=op.f('customers_email_key'))
    )
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_table('cars',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('current_location_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vin', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('plate_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('brand', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('production_year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('color', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('fuel_type', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('transmission', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('seats', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('mileage', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('daily_rate', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DateTime(), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.DateTime(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['current_location_id'], ['locations.id'], name=op.f('cars_current_location_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('cars_pkey')),
    sa.UniqueConstraint('plate_number', name=op.f('cars_plate_number_key')),
    sa.UniqueConstraint('vin', name=op.f('cars_vin_key'))
    )
    op.create_index(op.f('ix_cars_id'), 'cars', ['id'], unique=False)
    op.create_table('rentals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('car_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pickup_location_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('return_location_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('discount_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DateTime(), autoincrement=False, nullable=False),
    sa.Column('planned_end_date', sa.DateTime(), autoincrement=False, nullable=False),
    sa.Column('actual_end_date', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('base_cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('discount_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('total_cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('invoice_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('invoice_issue_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('paid_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('payment_method', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('payment_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('paid_at', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DateTime(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], name=op.f('rentals_car_id_fkey')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('rentals_customer_id_fkey')),
    sa.ForeignKeyConstraint(['discount_id'], ['discounts.id'], name=op.f('rentals_discount_id_fkey')),
    sa.ForeignKeyConstraint(['pickup_location_id'], ['locations.id'], name=op.f('rentals_pickup_location_id_fkey')),
    sa.ForeignKeyConstraint(['return_location_id'], ['locations.id'], name=op.f('rentals_return_location_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('rentals_pkey'))
    )
    op.create_index(op.f('ix_rentals_id'), 'rentals', ['id'], unique=False)
    op.drop_table('invoice')
    op.drop_table('rental')
    op.drop_table('car')
    op.drop_table('location')
    op.drop_table('customer')
    op.drop_table('transmission')
    op.drop_table('rental_status')
    op.drop_table('payment_status')
    op.drop_table('payment_method')
    op.drop_table('invoice_status')
    op.drop_table('fuel_type')
    op.drop_table('discount')
    op.drop_table('car_type')
    op.drop_table('car_status')
    op.drop_table('address')
    # ### end Alembic commands ###
